### ISSUE TITLE
Error while setting up growstuff platform for sensor - username not found.

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/homeassistant-growstuff#1]
Error while setting up growstuff platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/growstuff/sensor.py", line 18, in setup_platform
    member = requests.get(member_url).json().get('data')[0]
IndexError: list index out of range

```
https://www.growstuff.org/api/v1/members/?filter[login-name]=clockwerx
```

vs

```
https://www.growstuff.org/api/v1/members/?filter[login-name]=CloCkWeRX
```

**Comment by CloCkWeRX** [comment]
Fixed, I think.
